version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  server:
    build: ./server
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - auth
    environment:
      - MONGODB_URI=mongodb://mongo:27017/echo
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - AUTH_URL=http://auth:8080
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    environment:
      - VITE_SOCKET_URL=http://server:3000

  auth:
    build: ./auth-rs
    restart: unless-stopped
    environment:
      - JWT_SECRET=change-me
      - PORT=8080
      - RUST_LOG=info
    ports:
      - '8080:8080'

volumes:
  mongo-data:

  redis-data:
